### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by PEDROJOSEGIL** [wmjordan/SharpMuPDF#2]
Thank you very much and also for updating your repository to the latest 1.20 version of MuPDF.

Greetings,
Pedro Gil

**Comment by wmjordan** [comment]
Thank you for notifying me the released 1.20.
I have some difficulty pulling the repository from GitHub. I will keep this repository in sync when possible.

**Comment by wmjordan** [comment]
I've just released a new version with MuPDF 1.20.0.
