### ISSUE TITLE
VS2019 vs. VS2022

### ISSUE THREAD

**Issue by PEDROJOSEGIL** [wmjordan/SharpMuPDF#3]
May I please ask you what version of VS you have used to compile the MuPDF solution? VS2019? VS2022?

Have you tried to compile it with VS2022?

Thank you very much.

**Comment by wmjordan** [comment]
I compiled it with VS 2022.

We have to "retarget" the solution to make the compilation work.

**Comment by PEDROJOSEGIL** [comment]
Thank you. I will try it.

Greetings.
