### ISSUE TITLE
1.21.0

### ISSUE THREAD

**Issue by PEDROJOSEGIL** [wmjordan/SharpMuPDF#4]
Thank you very much for updating your repository. Just to let you know that the 1.21.0-rc1 version has already been published, although you are very likely aware of it. Thanks. ;-)

**Comment by wmjordan** [comment]
Thank you for reminding.
Unfortunately I have difficulty updating all sub-repositories. Thus it can take some days...

**Comment by PEDROJOSEGIL** [comment]
I understand it. Don't worry. Have a nice day!

**Comment by wmjordan** [comment]
It appeared to successfully pull all sub-modules of mupdf today.
I will try to compile the projects and see whether a new version is possible.

**Comment by PEDROJOSEGIL** [comment]
Great!!

**Comment by wmjordan** [comment]
Sorry for taking too long.
Eventually I found a way to get in sync with the mupdf project. And I have just updated this repository to 1.21.1.
Release will be coming soon.

**Comment by PEDROJOSEGIL** [comment]
Wonderful! Thank you so much.
