### ISSUE TITLE
MuPDFLib.X64.dll 的 pdf_to_name 方法调用异常

### ISSUE THREAD

**Issue by FlamHaze** [wmjordan/SharpMuPDF#5]
如题，在生成的x64dll调用pdf_to_name方法程序会直接闪退，该问题在1.20.0版本和1.21.1版本均存在

**Comment by wmjordan** [comment]
你的 P/Invoke 代码是怎样写的？

**Comment by FlamHaze** [comment]
[DllImport(DLL, CallingConvention = CC.Cdecl, EntryPoint = "pdf_to_name")]
public static extern string ToName(ContextHandle context, IntPtr obj);

该问题的发现来源于补丁丁更换x64的mupdf引擎后，某些pdf打开就闪退。最后定位是因为这些pdf含有特殊的页码名称，对于这种pdf您是通过 特殊页码名称 / 第n页展示的，如 II / 第2页。通过断点跟进，问题在PageLabelCollection的第22行：
var s = d["S"].NameValue;

这个NameValue的获取就是调用的mupdf的pdf_to_name

**Comment by wmjordan** [comment]
PDF补丁丁现在还没支持64位呢

**Comment by FlamHaze** [comment]
那没事了，您辛苦

**Comment by wmjordan** [comment]
如果PDF文档不包含页码标签，文档是否能正常显示呢？

**Comment by FlamHaze** [comment]
不包含页码标签，可以正常显示。

但是这并不意味着不包含页码标签的文档可以调用成功pdf_to_name，不包含页面标签在PageLabelCollection的第16行不会进入if判断，所以可以正常显示。

**Comment by wmjordan** [comment]
用32位版本的PDF补丁丁能正常显示那些带有页码标签的文档吗？

**Comment by FlamHaze** [comment]
可以正常显示，所以我只汇报了64位的MuPDFLib.dll 的 pdf_to_name 方法调用异常

**Comment by wmjordan** [comment]
等我有空更新MuPDF到1.22再看看

**Comment by wmjordan** [comment]
日前编译了 1.22 的新版，请测试一下新版本是否能工作
