### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by PEDROJOSEGIL** [wmjordan/SharpMuPDF#6]
Hi wmjordan,

May I please ask you some questions?

1) I see that your latest gen_libmupdf.def.py has this code on top of the file: **import os, re**, but in the past was: **import os, re, util**. Does it work for you without **util**?

2) Is it necessary to include **util.py** in the scripts directory as in the past?

3) Does it work Python 3 with the above file(s) or is it better Python 2.7.18?

Thank you very much.

**Comment by wmjordan** [comment]
`util` is not necessary. It is safe to remove it. I am going to push a new commit to eliminate it.

Either Python 3 or Python 2 should work actually.
I just upgraded the Python on my computer to Python 3 and modified the py script to work on it.

**Comment by PEDROJOSEGIL** [comment]
Thank you for your comments.

Could you please let me know what changes should be done to gen_libmupdf.def.py to work without **util** and with Python 3?

Until now, the only scenario that works for me is to use **util** along with Python 2.7.18. If I change one of those elements, it doesn't work for me.

Thank you.

**Comment by wmjordan** [comment]
Just use my source code.
Everything should be fine.

How "it doesn't work" appears on your side?

**Comment by PEDROJOSEGIL** [comment]
**How "it doesn't work" appears on your side?**

The only scenario that works for me, that is, the only way to run gen_libmupdf.def.py to create libmupdf.def in ..\platform\win32\MuPDFLib is when using **util** and Python 2.7.18.

If I delete **util** in gen_libmupdf.def.py while using Python 2.7.18, it does nothing, it does not create libmupdf.def.

If I use Python 3.11.3 (latest one) and run gen_libmupdf.def.py, it does nothing no matter using or not **util**.

I don't know the reason why it doesn't work for me when deleting **util** and using Python 3.

Any suggestion? Thanks.

**Comment by wmjordan** [comment]
My command line is:
````
D:\SharpMuPDF\MuPDFLib>python gen_libmupdf.def.py
````

I even eliminated all other paths and kept only the Python path in the `%path%` environment variable while I tested the above command. And my `%pathext%` did not contain any `.PY` or `.PYC` either.

Nothing went wrong.

My Python version is 3.10.10.

**Comment by PEDROJOSEGIL** [comment]
Thank you very much for your help and patience.

Eventually, I've been able to solve it. I had a problem in the %path% environment variable. Everything goes well. ;-)

Thank you once again.
