### ISSUE TITLE
gen_libmupdf.def.py

### ISSUE THREAD

**Issue by PEDROJOSEGIL** [wmjordan/SharpMuPDF#7]
Hello,

Thank you very much for updating it to 1.22.1. May I please ask you just a couple of questions about the updated gen_libmupdf.def.py?

I see that you include instructions related to jbig2_. Are they needed to get MuPDFLib.DLL?

I also see new misc functions such as "fz_log_errorFL", "fz_log_error_printfFL", "fz_morph_errorFL", "fz_rethrowFL", "fz_rethrow_ifFL", "fz_throwFL", "fz_vlog_error_printfFL", "fz_vthrowFL", "fz_vwarnFL", "fz_warnFL". Are all needed to get MuPDLib.DLL?

Thank you very much.

Warm regards,
Pedro Gil

**Comment by wmjordan** [comment]
Those `jbig2_` functions are supposed to be reused in my another project (some PDF projects might love to have those functions included), thus I exported them.

The functions with `fz_*FL` pattern are mistakenly placed in the file. You can safely remove them.

**Comment by PEDROJOSEGIL** [comment]
Thank you very much.

;-)
