### ISSUE TITLE
Hi, thx for your excellent work, since mupdf generated lib is too large, if want to shrink mupdf libmupdf.lib libresources.lib and libthirdparty.lib, what should i do ?

### ISSUE THREAD

**Issue by meiguoofa** [wmjordan/SharpMuPDF#9]
I only need mupdf's fitz module.  looking forward to your reply :)

**Comment by wmjordan** [comment]
Have you read the "Shrinking MuPDF.dll" section in the readme of this repository?

**Comment by wmjordan** [comment]
I am not familiar with C.
I know little about shrinking lib files.
It just works like that. You can't expect the C compiler generates as little as the C# compiler.

**Comment by meiguoofa** [comment]
Yes, I followed the steps you described in that section, but it doesn't seem to be working as expected. However, I've tried some alternative approaches to resolve the issue. Thank you for your response!！

**Comment by wmjordan** [comment]
Great to hear that.
How did you make it?

**Comment by meiguoofa** [comment]
> Great to hear that. How did you make it?

As this [Link](https://stackoverflow.com/questions/38168518/mupdf-compile-with-only-pdf-support) and you described in "Shrinking MuPDF.dll" section,  I disabled all unnecessary features in the config.h and removed any extraneous modules and code. However, since MuPDF is licensed under the AGPL, which isn't permissible for my company’s project, I decided to switch to PDFium instead. :)
